DROP TABLE IF EXISTS REGISTERED_CLASSES;
DROP TABLE IF EXISTS YOGA_CLASSES;
DROP TABLE IF EXISTS YOGA_CLASS_INFO;
DROP TABLE IF EXISTS "USER";

CREATE TABLE "USER" (
  ID SERIAL PRIMARY KEY NOT NULL,
  FULLNAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  USER_PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE REGISTERED_CLASSES (
  ID SERIAL PRIMARY KEY NOT NULL,
  USER_ID INTEGER REFERENCES "USER"(ID) ON DELETE CASCADE,
  YOGA_CLASS_ID INTEGER REFERENCES YOGA_CLASSES(ID) ON DELETE CASCADE,
  IS_PAID BOOLEAN 
); 

CREATE TABLE YOGA_CLASS_INFO (
  ID SERIAL PRIMARY KEY NOT NULL,
  CLASS_NAME VARCHAR(255) NOT NULL,
  PRICE VARCHAR(255) NOT NULL,
  DETAILS VARCHAR(255) NOT NULL,
  DURATION VARCHAR(255) NOT NULL,
  MAX_CAPACITY INTEGER NOT NULL
);

CREATE TABLE YOGA_CLASSES (
  ID SERIAL PRIMARY KEY NOT NULL,
  YOGA_CLASS_INFO_ID INTEGER REFERENCES YOGA_CLASS_INFO(ID) ON DELETE CASCADE,
  CLASS_DAY VARCHAR(255) NOT NULL,
  START_TIME VARCHAR(255) NOT NULL,
  IS_MAX_CAPACITY BOOLEAN,
  CLASS_TYPE INTEGER REFERENCES YOGA_CLASS_INFO(ID)
  -- Class type has to be the same as yoga_class_info(class_name)
);
